import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "";
    callback divide-income(string);


    background: bisque;
    GridLayout {
        padding: 20px;
        
        Row {
            
            Text {
                text: "MY INCOME STATS";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
                color: black;
            }
        }
        Row {
            income:=LineEdit {
                placeholder-text: "Enter your money";
                font-size: 16px;
                height: 35px;    
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 35px;  
                clicked => {
                    divide-income(income.text);
                }
            }
            
        }
        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: whitesmoke;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500; 
                        text: root.results;
                    }
                }
            }
        }
    }
}
